# Generated by Django 3.1.2 on 2020-10-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.TextField()),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='Personal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessExpert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='expert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gratitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('Sentance', models.TextField()),
                ('via', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GymGallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Cardio', 'Cardio Classes'), ('Swimming', 'Swimming Lesson'), ('Yoga', 'Yoga Classes'), ('Aerobics', 'Aerobics'), ('Zumba', 'Zumba'), ('Massage', 'Massage'), ('Body B', 'Body Building')], max_length=40)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='gym')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plans', models.CharField(choices=[('Starter', 'Starter'), ('Basic', 'Basic'), ('Pro', 'Pro'), ('Unlimited', 'Unlimited')], max_length=50)),
                ('price', models.IntegerField()),
                ('trainings', models.CharField(choices=[('Cardio', 'Cardio Classes'), ('Swimming', 'Swimming Lesson'), ('Yoga', 'Yoga Classes'), ('Aerobics', 'Aerobics'), ('Zumba', 'Zumba'), ('Massage', 'Massage'), ('Body B', 'Body Building')], max_length=50)),
                ('participating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SportProgramme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Cardio', 'Cardio Classes'), ('Swimming', 'Swimming Lesson'), ('Yoga', 'Yoga Classes'), ('Aerobics', 'Aerobics'), ('Zumba', 'Zumba'), ('Massage', 'Massage'), ('Body B', 'Body Building')], max_length=30)),
                ('long_descr', models.TextField()),
                ('short_descr', models.TextField()),
                ('img', models.ImageField(upload_to='programme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
