# Generated by Django 3.1.2 on 2020-10-31 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201031_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceservice',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.price'),
        ),
        migrations.RemoveField(
            model_name='priceservice',
            name='services',
        ),
        migrations.AddField(
            model_name='priceservice',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.service'),
        ),
    ]
