# Generated by Django 3.1.2 on 2020-11-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201102_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportprogramme',
            name='name',
            field=models.CharField(choices=[('Cardio', 'Cardio Classes'), ('Swimming', 'Swimming Lesson'), ('Yoga', 'Yoga Classes'), ('Aerobics', 'Aerobics'), ('Zumba', 'Zumba'), ('Massage', 'Massage'), ('Body B', 'Body Building')], max_length=200),
        ),
    ]
