# Generated by Django 3.1.2 on 2020-11-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201102_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sportprogramme',
            name='name',
            field=models.CharField(choices=[('Cardio', 'Cardio Classes'), ('Swimming', 'Swimming Lesson'), ('Yoga', 'Yoga Classes'), ('Aerobics', 'Aerobics'), ('Zumba', 'Zumba'), ('Massage', 'Massage'), ('Body Building ', 'Body Building')], max_length=200),
        ),
    ]
