# Generated by Django 3.1.2 on 2020-11-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201103_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='gratitude',
            name='img',
            field=models.ImageField(null=True, upload_to='circle'),
        ),
    ]
