# Generated by Django 3.1.2 on 2020-11-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_gratitude_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='username',
            name='surname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
