# Generated by Django 3.1.2 on 2020-11-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201103_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
