# Generated by Django 3.1.2 on 2020-11-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201110_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='traings',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
