# Generated by Django 3.1.2 on 2020-11-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_traings_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='full_descr',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_descr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
